version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.8.13-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  action:
    image: <image:tag>
    expose: 5055
    
  duckling:
    image: rasa/duckling
    ports: 8000:8000 
  
  SQLTrackerStore:
    image:
    
  event-broker:
    image:
    
  RedisLockStore:
    image:


